# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security_test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
    - name: Use Node.js v20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Execute security tests
      run: npm audit

  build_test:
    needs: security_test
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
    - name: Use Node.js v20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: run npm install
      run: npm install
    - name: run tests
      run: npm test

  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true